// Test-only Better Auth instance. Used by the integration test suite.
//
// This file is excluded from the production build (see tsconfig.json;
// the build include is src plus ** slash star .ts but this file is
// imported only from tests). The tsconfig.test.json includes it for
// type-checking.
// 
// What this differs from auth.ts:
//   - PGlite instead of postgres-js for the DB (in-memory, zero-setup).
//   - testUtils() plugin for factories, DB helpers, auth helpers, OTP capture.
//   - Simplified config: no cross-subdomain cookies, no rate limit,
//     deterministic secret, no real OAuth providers.
//   - Same RBAC matrix as prod (we want to test RBAC end-to-end).
//
// To run: pnpm --filter at-deessejs/auth test.

import { betterAuth } from 'better-auth'
import { drizzleAdapter } from '@better-auth/drizzle-adapter'
import { testUtils } from 'better-auth/plugins'
import { organization, twoFactor, magicLink, emailOTP, admin } from 'better-auth/plugins'
import { passkey } from '@better-auth/passkey'
import { apiKey } from '@better-auth/api-key'
import { PGlite } from '@electric-sql/pglite'
import { drizzle } from 'drizzle-orm/pglite'
import { migrate } from 'drizzle-orm/pglite/migrator'
import { resolve } from 'node:path'
import { schema } from '@deessejs/database'

import { ac, owner, admin as adminRole, member, billing } from './access-control'

// ─── In-memory Postgres via PGlite ────────────────────────────────
const client = new PGlite()
const db = drizzle({ client })

// Apply migrations generated by `drizzle-kit generate` in packages/database.
// Path is relative to THIS file (packages/auth/src/auth.test.ts).
//   ../      → packages/auth/src/../
//   ../../   → packages/
//   ../../database/src/migrations  → ✓
await migrate(db, {
  migrationsFolder: resolve(import.meta.dirname, '../../database/src/migrations'),
})

// ─── Better Auth instance ────────────────────────────────────────
export const auth = betterAuth({
  appName: 'DeesseJS Test',
  basePath: '/api/auth',
  baseURL: 'http://localhost:3000',
  // Deterministic secret for tests. 32+ chars required.
  secret: 'test-secret-at-least-32-chars-long-for-integration-tests-only',

  database: drizzleAdapter(db, {
    provider: 'pg',
    schema,
    usePlural: true,
  }),

  // === Email & password ===
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: false, // simpler — flow tests cover verification
    sendResetPassword: async () => {
      // no-op in tests; we capture via testUtils if needed
    },
  },

  // === Email verification ===
  emailVerification: {
    sendVerificationEmail: async () => {},
    autoSignInAfterVerification: true,
  },

  // === Magic link ===
  magicLink: {
    enabled: true,
    sendMagicLink: async () => {},
    expiresIn: 60 * 10,
  },

  // === Email OTP ===
  emailOTP: {
    enabled: true,
    otpLength: 6,
    expiresIn: 60 * 10,
    sendVerificationOTP: async () => {},
  },

  // === OAuth providers (dummy creds for typecheck; not actually invoked) ===
  socialProviders: {
    google: { clientId: 'test-google', clientSecret: 'test-google' },
    github: { clientId: 'test-github', clientSecret: 'test-github' },
  },

  // === Sessions ===
  session: {
    expiresIn: 60 * 60 * 24 * 7,
    updateAge: 60 * 60 * 24,
    cookieCache: { enabled: false }, // disabled for simpler test assertions
    storeSessionInDatabase: true,
  },

  // === Cookies ===
  advanced: {
    crossSubDomainCookies: { enabled: false }, // simpler for tests
    defaultCookieAttributes: {
      sameSite: 'lax',
      httpOnly: true,
    },
    useSecureCookies: false,
  },

  // === Rate limit disabled in tests ===
  rateLimit: { enabled: false },
  secondaryStorage: {
    get: async () => null,
    set: async () => {},
    delete: async () => {},
  },

  // === Plugins (same as prod, plus testUtils) ===
  plugins: [
    organization({
      ac,
      roles: { owner, admin: adminRole, member, billing },
      allowUserToCreateOrganization: true,
    }),
    admin({ defaultRole: 'member', adminRoles: ['admin'] }),
    apiKey({ defaultPrefix: 'sk_test_', rateLimit: { enabled: false } }),
    twoFactor({ issuer: 'DeesseJS Test' }),
    passkey({
      rpName: 'DeesseJS Test',
      rpID: 'localhost',
      origin: 'http://localhost:3000',
    }),
    // ★ Test helpers — factories, DB helpers, auth helpers, OTP capture ★
    testUtils({ captureOTP: true }),
  ],
})

export type TestAuth = typeof auth
