/**
 * Schema assembly point.
 *
 * The Drizzle client (see `client.ts`) imports the `schema` object from
 * this file. Every table — whether generated by Better Auth or hand-written
 * per feature — ends up in the namespace.
 *
 * Exports two shapes:
 *   - The `schema` namespace object (used by drizzle config + drizzleAdapter)
 *   - Individual re-exports (for direct imports: `import { users } from '@deessejs/database'`)
 *
 * The Better Auth CLI (`pnpm auth:generate`) generates a single file with
 * all pgTable definitions + per-table relations at `./auth/index.ts`.
 * Per-feature schemas (M1+) will follow the same pattern.
 */
import * as authSchema from './auth'

export const schema = {
  ...authSchema,
}

// Re-export column builders + ID types (not tables, used by procedures)
export * from './_columns'

// Re-export all auth tables + relations (so consumers can do `import { users, usersRelations }`)
export * from './auth'
